name: Hello World  # このworkflowの名前

# on: # onで実行タイミングを設定
#   workflow_dispatch: # 手動で実行するAction

on: [push]

jobs: # jobsで実行する内容を書く
  say_hello: # 実行する内容(job)の名前
    runs-on: ubuntu-latest # 実行するOS
    steps:
      - run: npm i
      - run: npm run build